docker: docker
dkr: docker
dockerfile: dockerfile
ansible: ansible
amazon: aws
aws: aws
gRPC: gRPC
gcp: gcp
cloudformation: cloudformation
cfn: cloudformation
azure: azure
arm: arm
alicloud: alicloud
tf: terraform
terraform: terraform
openapi: openapi
kubernetes: kubernetes
k8s: kubernetes
pulumi: pulumi