project_name: kics

builds:
  - main: ./cmd/console/main.go
    id: "cli"
    binary: cli
    goos:
      - linux
      - windows 
    goarch:
      - amd64
archives:
  builds: [kics]
  format_overrides:
    - goos: windows
        format: zip
  replacements:
    amd64: x64
    386: x32
      