project_name: kics

builds:
  - main: ./cmd/console/main.go
    binary: kics
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: linux
        goarm: 6
    ldflags:
      - -X github.com/Checkmarx/kics/internal/constants.Version={{.Version}}
      - -X github.com/Checkmarx/kics/internal/constants.SCMCommit={{.Commit}}
archives:
  - builds: [kics]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
      - assets/queries/**/metadata.json
      - assets/queries/**/*.rego
      - assets/libraries
brews:
  - tap:
      owner: checkmarx
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/Checkmarx/kics
    description: Find security vulnerabilities, compliance issues, and infrastructure misconfigurations in your IaC
    license: Apache
    test: |
      system "#{bin}/kics version"
    install: |-
      pkgshare.mkpath
      cp_r "assets", pkgshare
      bin.install "kics"
    custom_block: |
      def caveats
        <<~EOS
          To use KICS default queries add KICS_QUERIES_PATH env to your ~/.zshrc or ~/.zprofile:
              "echo 'export KICS_QUERIES_PATH=#{pkgshare}/assets/queries' >> ~/.zshrc"
        EOS
      end
release:
  prerelease: true
