project_name: kics

builds:
  - main: ./cmd/console/main.go
    binary: kics
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -X github.com/Checkmarx/kics/internal/constants.Version={{ .Version }}-{{ .ShortCommit }}
      - -X github.com/Checkmarx/kics/internal/constants.SCMCommit={{ .Commit }}
      - -X github.com/Checkmarx/kics/internal/constants.SentryDSN={{ .Env.SENTRY_DSN }}
archives:
  - builds: [kics]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
      - assets/queries
      - assets/libraries
release:
  prerelease: true
snapshot:
  name_template: nightly
