project_name: kics

builds:
  - main: ./cmd/console/main.go
    id: "cli"
    binary: cli
    goos:
      - linux
      - windows 
    goarch:
      - amd64
archives:
  builds:
  - default
  format_overrides:
      - goos: windows
        format: zip
      