project_name: kics

builds:
  - main: ./cmd/console/main.go
    binary: kics
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
      - -s
      - -w
      - -X github.com/Checkmarx/kics/internal/constants.Version={{ .Version }}-{{ .ShortCommit }}-{{ .Date }}
      - -X github.com/Checkmarx/kics/internal/constants.SCMCommit={{ .Commit }}
      - -X github.com/Checkmarx/kics/internal/constants.SentryDSN={{ .Env.SENTRY_DSN }}
      - -X github.com/Checkmarx/kics/internal/constants.BaseURL={{ .Env.DESCRIPTIONS_URL }}
      - -X github.com/Checkmarx/kics/internal/constants.APIScanner={{ .Env.APISCANNER }}
archives:
  - builds: [kics]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
      - assets/queries/openAPI/**/metadata.json
      - assets/queries/openAPI/**/*.rego
      - assets/queries/common/**/metadata.json
      - assets/queries/common/**/*.rego
      - assets/libraries/openapi
      - assets/libraries/common
release:
  prerelease: true
snapshot:
  name_template: apispec
