ignore:
  - package:
      name: anchore/scan-action
  - package:
      location: "/root/.terraform.d/plugins/linux_amd64/terraform-provider-**"
  - package:
      location: "/usr/bin/terraform"
  - package:
      location: "/usr/local/bin/terraform"
