ignore:
  - package:
      name: anchore/scan-action
  - package:
      location: "/root/.terraform.d/plugins/linux_amd64/terraform-provider-**"
  - package:
      location: "/usr/bin/terraform"
  - package:
      location: "/usr/local/bin/terraform"
  - vulnerability: GHSA-6m8w-jc87-6cr7 # Not Exploitable -> we don't run OPA as a server on KICS (opa run --server)
exclude:
  - './.github/scripts/**' # test files
