package Cx

import data.generic.common as common_lib
import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resources := input.document[i].Resources[name]
	resources.Type == "AWS::KMS::Key"
	properties := resources.Properties
	rotation_eligible(properties)
	cf_lib.isCloudFormationFalse(properties.EnableKeyRotation)

	result := {
		"documentId": input.document[i].id,
		"resourceType": resources.Type,
		"resourceName": cf_lib.get_resource_name(resources, name),
		"searchKey": sprintf("Resources.%s.Properties.EnableKeyRotation", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s.Properties.EnableKeyRotation should not be 'true'", [name]),
		"keyActualValue": sprintf("Resources.%s.Properties.EnableKeyRotation is true", [name]),
	}
}

CxPolicy[result] {
	resources := input.document[i].Resources[name]
	resources.Type == "AWS::KMS::Key"
	properties := resources.Properties
	rotation_eligible(properties)
	not common_lib.valid_key(properties, "EnableKeyRotation")

	result := {
		"documentId": input.document[i].id,
		"resourceType": resources.Type,
		"resourceName": cf_lib.get_resource_name(resources, name),
		"searchKey": sprintf("Resources.%s.Properties.EnableKeyRotation", [name]),
		"issueType": "MissingAttribute",
		"keyExpectedValue": sprintf("Resources.%s.Properties.EnableKeyRotation should be defined", [name]),
		"keyActualValue": sprintf("Resources.%s.Properties.EnableKeyRotation is undefined", [name]),
	}
}

# AWS automatic key rotation only applies to symmetric encryption keys whose key
# material was generated by KMS. Asymmetric keys, HMAC keys and keys with an
# imported (EXTERNAL) key origin do not support EnableKeyRotation, so they must
# not be flagged here.
rotation_eligible(properties) {
	key_spec(properties) == "SYMMETRIC_DEFAULT"
	key_origin(properties) != "EXTERNAL"
}

# KeySpec defaults to SYMMETRIC_DEFAULT when it is not set.
key_spec(properties) = spec {
	common_lib.valid_key(properties, "KeySpec")
	spec := upper(properties.KeySpec)
} else = "SYMMETRIC_DEFAULT" {
	true
}

# Origin defaults to AWS_KMS (KMS-generated material) when it is not set.
key_origin(properties) = origin {
	common_lib.valid_key(properties, "Origin")
	origin := upper(properties.Origin)
} else = "AWS_KMS" {
	true
}
