version: 2.1
jobs:
  kics:
    docker:
      - image: checkmarx/kics:latest-alpine
    steps:
      - checkout
      - run:
          name: Run KICS
          command: |
            /app/bin/kics scan -p ${PWD} -o ~/results.json --ci
      - store_artifacts:
          path: ~/results.json

workflows:
  version: 2
  build:
    jobs:
      # etc...
      - kics
