FROM adoptopenjdk/openjdk11:alpine@sha256:b11c19251c5174d449d67793c9b18f729b209c0030f25f9a127b3c96b519c131 AS builder

WORKDIR /opt/antlr4

ARG ANTLR_VERSION="4.13.1"
ARG MAVEN_OPTS="-Xmx1G"

RUN apk add --no-cache maven git \
  && git clone https://github.com/antlr/antlr4.git \
  && cd antlr4 \
  && git checkout $ANTLR_VERSION \
  && mvn clean --projects tool --also-make \
  && mvn -DskipTests install --projects tool --also-make \
  && mv ./tool/target/antlr4-*-complete.jar antlr4-tool.jar

FROM adoptopenjdk/openjdk11:alpine-jre@sha256:ed992fd62dc87ba31aea960de3a664b932776b0ba55161936840690cd7c83191

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000

RUN adduser \
  --disabled-password \
  --gecos "" \
  --home "$(pwd)" \
  --no-create-home \
  --uid "${uid}" \
  "${user}"

COPY --from=builder /opt/antlr4/antlr4/antlr4-tool.jar /usr/local/lib/

WORKDIR /work

ENTRYPOINT ["java", "-Xmx500M", "-cp", "/usr/local/lib/antlr4-tool.jar", "org.antlr.v4.Tool"]

CMD [ "-Dlanguage=Go", "-visitor", "-no-listener", "-o", "parser", "jsonfilter/JSONFilter.g4", "-Dlanguage=Go", "-visitor", "-no-listener", "-o", "parser", "bicep/antlr/bicep.g4"]
