FROM golang:1.26.2@sha256:b54cbf583d390341599d7bcbc062425c081105cc5ef6d170ced98ef9d047c716 AS go_toolchain

FROM redhat/ubi8:latest@sha256:a94c5e31450d30190afe6f7a09628dd1dd7a3dc98784ba5ed1d19fd77098fcb2 AS build_env

ARG TARGETOS
ARG TARGETARCH

WORKDIR /build

ENV PATH=$PATH:/usr/local/go/bin

COPY --from=go_toolchain /usr/local/go /usr/local/go

ENV GOPRIVATE=github.com/Checkmarx/*
ARG VERSION="development"
ARG COMMIT="NOCOMMIT"
ARG SENTRY_DSN=""
ARG DESCRIPTIONS_URL=""

# Copy go mod and sum files
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download -x

# COPY the source code as the last step
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build \
  -ldflags "-s -w -X github.com/Checkmarx/kics/v2/internal/constants.Version=${VERSION} -X github.com/Checkmarx/kics/v2/internal/constants.SCMCommit=${COMMIT} -X github.com/Checkmarx/kics/v2/internal/constants.SentryDSN=${SENTRY_DSN} -X github.com/Checkmarx/kics/v2/internal/constants.BaseURL=${DESCRIPTIONS_URL}" \
  -a -installsuffix cgo \
  -o bin/kics cmd/console/main.go

FROM redhat/ubi8:latest@sha256:a94c5e31450d30190afe6f7a09628dd1dd7a3dc98784ba5ed1d19fd77098fcb2

ARG RELEASE
ARG VERSION

ENV RELEASE=$RELEASE \
  VERSION=$VERSION

LABEL name="KICS" \
  summary="Provides the latest release of the KICS (Keeping Infrastructure as Code Secure) scanner" \
  description="Checkmarx/kics is an opensource project that enable you to find security vulnerabilities, compliance issues, and infrastructure misconfigurations early in the development cycle of your infrastructure-as-code find more in https://kics.io" \
  maintainer="kics@checkmarx.com" \
  vendor="Checkmarx" \
  version="v2.1.21" \
  release="1" \
  io.k8s.display-name="KICS by Checkmarx" \
  io.openshift.tags="kics checkmarx"

ARG KUSER=kics
ARG KGROUP=kics
ARG UID=1000
ARG GID=1000

RUN yum install git wget unzip -y \
  && groupadd -g ${GID} ${KGROUP} \
  && adduser \
  --home-dir /app/bin \
  --no-create-home \
  --uid ${UID} \
  -g ${KGROUP} \
  -s /bin/bash \
  ${KUSER}

USER ${KUSER}

COPY LICENSE /licenses/LICENSE

WORKDIR /app/bin

# Copy built binary to the runtime container
COPY --chown=${KUSER}:${KGROUP} --from=build_env /build/bin/kics /app/bin/kics
COPY --chown=${KUSER}:${KGROUP} --from=build_env /build/assets/ /app/bin/assets/

ENV PATH=$PATH:/app/bin

# Command to run the executable
ENTRYPOINT ["/app/bin/kics"]
