# Include this file in your .gitlab-ci.yml file to automate & integrate Checkmarx KICS' security scans.
#
# include documentation https://docs.gitlab.com/ee/ci/yaml/includes.html
#
# defined as in https://docs.gitlab.com/ee/development/cicd/templates.html#versioning
#
image:
  name: checkmarx/kics:latest
  entrypoint: [""]

stages:
  - kics

kics-scan:
  stage: kics
  script:
    - kics scan -q /app/bin/assets/queries -p ${PWD} --ignore-on-exit all --report-formats glsast -o ${PWD} --output-name kics-results --ci
  artifacts:
    reports:
      sast: gl-sast-kics-results.json
    when: always
