# Include this file in your .gitlab-ci.yml file to automate & integrate Checkmarx KICS' security scans.
#
# include documentation https://docs.gitlab.com/ee/ci/yaml/includes.html
#
# defined as in https://docs.gitlab.com/ee/development/cicd/templates.html#versioning
#
image: alpine

before_script:
  - apk add --no-cache libc6-compat curl
  - DATETIME="`date '+%H:%M'`"
  - TAG=`curl --silent "https://api.github.com/repos/Checkmarx/kics/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
  - echo "${DATETIME} - INF latest tag is $TAG"
  - VERSION=`echo $TAG | sed -r 's/^.{1}//'`
  - echo "${DATETIME} - INF version is $VERSION"
  - echo "${DATETIME} - INF downloading latest kics binaries kics_${VERSION}_linux_x64.tar.gz"
  - wget -q -c "https://github.com/Checkmarx/kics/releases/download/${TAG}/kics_${VERSION}_linux_x64.tar.gz" -O - | tar -xz --directory /usr/bin &>/dev/null

stages:
  - kics

kics-scan:
  stage: kics
  script:
    - kics scan --no-progress -q /usr/bin/assets/queries -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results --fail-on high
  artifacts:
    name: kics-results.json
    when: always
    paths:
      - kics-results.json
