image:
  name: checkmarx/kics:latest
  entrypoint: [""]

stages:
  - kics

kics-scan:
  stage: kics
  script:
    - kics scan -q /app/bin/assets/queries -p ${PWD} --ignore-on-exit all --report-formats glsast -o ${PWD} --output-name kics-results
  artifacts:
    reports:
      sast: gl-sast-kics-results.json
    when: always
