version: 2.1
orbs:
  gh: circleci/github-cli@1.0.5
executors:
  circle-machine:
    machine:
      image: ubuntu-2004:2023.04.2
  cimg-base:
    docker:
      - image: cimg/base:2022.11
    resource_class: small

jobs:
  publish-github-release-and-images:
    executor: circle-machine
    working_directory: ~/repo
    steps:
      - run:
          name: Config git and clone kics-queries-repo
          command: |
            git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
            git clone https://github.com/CheckmarxDev/kics-queries-repo.git full_repo
      - run:
          name: Configure tools worktree
          command: |
            cd full_repo
            git worktree add ../main main
            cd ..
      - run:
          name: Set variables
          command: |
            echo "branch_name_template_to_replace" >> main/releaseBranches.txt
            main/scripts/setVariables.sh
            source "$BASH_ENV"
      - run:
          name: Build kics-queries-repo tar.gz
          command: |
            main/scripts/createQueriesRepo.sh "$PWD/full_repo" queries.tar.gz
      - run:
          name: Create GitHub release
          command: |
            main/scripts/createRelease.sh
      - run:
          name: Build ast-data image
          command: |
            main/scripts/buildImages.sh
      - run:
          name: Push ast-data image (JFrog Artifactory) 
          command: |
            main/scripts/pushImageJFrog.sh
      - run:
          name: Persist AST_DATA_TAG to env file
          command: |
            echo "export AST_DATA_TAG='${AST_DATA_TAG}'" > /tmp/ast_data_env
      - persist_to_workspace:
          root: "/tmp"
          paths:
            - ast_data_env

workflows:
  release-publish-workflow:
    jobs:
      - publish-github-release-and-images:
          filters:
            branches:
              only:
                - "branch_name_template_to_replace"
          context:
            - AWS
            - JFROG