from openjdk:10-jdk
volume /tmp
add http://source.file/package.file.tar.gz /temp
run tar -xjf /temp/package.file.tar.gz 
arg JAR_FILE
add ${JAR_FILE} app.jar
entrypoint ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
