package flags

// Flags constants for scan
const (
	BomFlag                 = "bom"
	CloudProviderFlag       = "cloud-provider"
	ConfigFlag              = "config"
	DisableFullDescFlag     = "disable-full-descriptions"
	ExcludeCategoriesFlag   = "exclude-categories"
	ExcludePathsFlag        = "exclude-paths"
	ExcludeQueriesFlag      = "exclude-queries"
	ExcludeResultsFlag      = "exclude-results"
	ExcludeSeveritiesFlag   = "exclude-severities"
	ExperimentalQueriesFlag = "experimental-queries"
	IncludeQueriesFlag      = "include-queries"
	InputDataFlag           = "input-data"
	FailOnFlag              = "fail-on"
	IgnoreOnExitFlag        = "ignore-on-exit"
	MinimalUIFlag           = "minimal-ui"
	NoProgressFlag          = "no-progress"
	OutputNameFlag          = "output-name"
	OutputPathFlag          = "output-path"
	PathFlag                = "path"
	PayloadPathFlag         = "payload-path"
	PreviewLinesFlag        = "preview-lines"
	QueriesPath             = "queries-path"
	LibrariesPath           = "libraries-path"
	ReportFormatsFlag       = "report-formats"
	TypeFlag                = "type"
	ExcludeTypeFlag         = "exclude-type"
	TerraformVarsPathFlag   = "terraform-vars-path"
	QueryExecTimeoutFlag    = "timeout"
	LineInfoPayloadFlag     = "payload-lines"
	DisableSecretsFlag      = "disable-secrets"
	SecretsRegexesPathFlag  = "secrets-regexes-path" //nolint:gosec
	ExcludeGitIgnore        = "exclude-gitignore"
	OpenAPIReferencesFlag   = "enable-openapi-refs"
	ParallelScanFile        = "parallel"
	MaxFileSizeFlag         = "max-file-size"
	UseOldSeveritiesFlag    = "old-severities"
	MaxResolverDepth        = "max-resolver-depth"
	KicsComputeNewSimIDFlag = "kics_compute_new_simid"
)
