#!/usr/bin/env python3

import json
import os
import subprocess
import sys
from pathlib import Path
from results_models import ScanResults

REPO_ROOT = Path(__file__).resolve().parents[3]


def get_changed_queries():
    """
    Parse CHANGED_QUERIES env var to get query directories.

    Expects a JSON array from dorny/paths-filter.
    """
    raw = os.getenv("CHANGED_QUERIES", "")
    if not raw:
        print("::error::CHANGED_QUERIES environment variable is empty or not set")
        sys.exit(1)

    try:
        files = json.loads(raw)
    except json.JSONDecodeError:
        print(f"::error::CHANGED_QUERIES is not valid JSON: {raw}")
        sys.exit(1)

    dirs = []
    for f in files:
        if f.endswith("/query.rego"):
            dirs.append(REPO_ROOT / Path(f).parent)
    return dirs


def has_search_line_defined(query_dir):
    """Check if query.rego defines searchLine in its result object."""
    rego_file = query_dir / "query.rego"
    if not rego_file.exists():
        return False
    return "searchLine" in rego_file.read_text()


def run_kics_scan(query_dir):
    """
    Run KICS scan for a single query.

    Returns True if the scan completed successfully.
    """
    query_id = json.loads((query_dir / "metadata.json").read_text())["id"]

    results_dir = query_dir / "results"
    results_dir.mkdir(exist_ok=True)

    payloads_dir = query_dir / "payloads"
    payloads_dir.mkdir(exist_ok=True)

    cmd = [
        "go",
        "run",
        str(REPO_ROOT / "cmd" / "console" / "main.go"),
        "scan",
        "-p",
        str(query_dir / "test"),
        "-o",
        str(results_dir),
        "--output-name",
        "all_results.json",
        "-i",
        query_id,
        "-d",
        str(payloads_dir / "all_payloads.json"),
        "-v",
        "--experimental-queries",
        "--bom",
        "--enable-openapi-refs",
        "--ignore-on-exit",
        "results",
        "--kics_compute_new_simid",
    ]

    print(f"  Running scan with query ID: {query_id}")

    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO_ROOT))

    if proc.returncode not in {0, 60, 50, 40, 30, 20}:
        print(f"  ::error::Scan failed (exit code {proc.returncode})")
        if proc.stdout:
            print(f"  stdout (last 500 chars): ...{proc.stdout[-500:]}")
        if proc.stderr:
            print(f"  stderr (last 500 chars): ...{proc.stderr[-500:]}")
        return False

    return True


def validate_scan_results(query_dir):
    """
    Validate scan results.

    - Fail if any search_line != line
    - Fail if any search_line == -1
    """
    results_file = query_dir / "results" / "all_results.json"
    rel_dir = query_dir.relative_to(REPO_ROOT)

    if not results_file.exists():
        print(f"  ::error file={rel_dir}::Results file not generated by scan")
        return False

    data = json.loads(results_file.read_text())
    scan_results = ScanResults(data)

    if scan_results.queries_failed_to_execute > 0:
        print(
            f"  ::error file={rel_dir}::{scan_results.queries_failed_to_execute} query(ies) failed to execute (possible panic/error during scan)"
        )
        return False

    # Flatten results from all queries
    all_results = []
    for query in scan_results.queries:
        all_results.extend(query.files)

    if not all_results:
        print("  [OK] No results to validate")
        return True
    # Validate each result
    valid = True
    for idx, f in enumerate(all_results):
        sl = int(f.search_line)
        ln = int(f.line)
        fn = f.file_name

        if sl == -1:
            print(f"  ::error::Result [{idx}] {fn}: search_line is -1")
            valid = False
        elif sl != ln:
            print(f"  ::error::Result [{idx}] {fn}: search_line ({sl}) != line ({ln})")
            valid = False
        else:
            print(f"  [OK] Result [{idx}] {fn}: search_line={sl} == line={ln}")

    return valid


def validate_query(query_dir):
    """Validate a single query directory."""
    if not has_search_line_defined(query_dir):
        print("  [SKIP] searchLine not defined in query.rego - PASS")
        return True

    print("  searchLine is defined in query.rego - running scan...")

    if not run_kics_scan(query_dir):
        return False

    return validate_scan_results(query_dir)


def main():
    print("Running script validate_search_line.py")
    query_dirs = get_changed_queries()

    if not query_dirs:
        print("No query.rego were changed - nothing to validate")
        sys.exit(0)

    all_valid = True
    for qd in query_dirs:
        if not validate_query(qd):
            all_valid = False

    if all_valid:
        print("All searchLine validations passed!")
        sys.exit(0)
    else:
        print("::error::Some searchLine validations failed. See errors above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
