name: check-go-coverage

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: generate-coverage
    runs-on: cx-public-ubuntu-x64
    outputs:
      coverage: ${{ steps.testcov.outputs.coverage }}
      color: ${{ steps.testcov.outputs.color }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #v6.3.0
        with:
          go-version-file: go.mod
      - name: Run test metrics script
        id: testcov
        run: |
          make test-coverage-report | tee test-results
          TOTAL_TESTS=$(cat test-results | grep -v TestQueriesContent/ | grep -v TestQueriesMetadata/ | grep -v TestQueries/ | grep PASS | wc -l)
          echo "Total number of tests :: ${TOTAL_TESTS}"
          echo "total_tests=${TOTAL_TESTS}" >> "$GITHUB_OUTPUT"
      - name: Checks if Go coverage is at least 74%
        env:
          GO_COVERAGE: ${{ steps.testcov.outputs.coverage }}
        if: ${{ env.GO_COVERAGE < 74 }}
        run: |
          echo "Go coverage is lower than 74%: ${GO_COVERAGE}%"
          exit 1
