name: init-versioning
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-bootswatch mike
      - run: |
          mike delete --all
          mike deploy 1.2.2 latest
          mike deploy develop
          mike set-default 1.2.2
