name: kics-github-action

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "./Dockerfile"
          ignore_on_exit: results
          enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
          exclude_queries: 67fd0c4a-68cf-46d7-8c41-bc9fba7e40ae # Ignore Last User Is 'root'
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: results
          path: ./results
