name: notification-update-flags

on:
  workflow_dispatch:
  # push:
  #   branches: [master]
  #   paths:
  #     - "internal/console/assets/*-flags.json"

jobs:
  notification-update-flags:
    name: Send email with flag changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Execute diff and send email
        run: |
          for item in internal/console/assets/*-flags.json; do cat $item > $item-curr; done;
          git checkout HEAD~1
          for item in internal/console/assets/*-flags.json; do cat $item > $item-old; done;
          printf -v curr "'%s'," internal/console/assets/*-flags.json-curr
          printf -v old "'%s'," internal/console/assets/*-flags.json-old
          python3 -u .github/scripts/watchers/change-flags-email.py \
            -n $(echo "${curr%,}") -o $(echo "${old%,}")
