name: release-kics-cxone
on:
  release:
    types:
      - published
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Git credentials
      run: |
          git config --global user.name "KICSBot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://${{ secrets.CHECKMARXDEV_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Clone internal repository
      run: |
          cd ..
          git clone https://github.com/CheckmarxDev/${{ secrets.CHECKMARXDEV_KICS_RELEASER }}.git

    - name: Create new branch for release ${{ github.event.release.name }}
      run: |
          cd ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}
          git checkout --orphan ${{ github.event.release.name }}
          find . -mindepth 1 \( -not -path './.*' -not -name 'README.md' -o -name '.gitignore' \) -delete

    - name: Copy queries to new branch
      run: |
          mkdir -p ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}/kics-queries
          rsync -av --exclude='*/test/*' --exclude='common/*' ./assets/queries/ ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}/kics-queries/

    - name: Modify circleci configuration
      run: |
          sed -i 's/BRANCH_NAME_TEMPLATE_TO_REPLACE/${{ github.event.release.name }}/g' ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}/.circleci/config.yml
          sed -i 's/BRANCH_NAME_TEMPLATE_TO_REPLACE/${{ github.event.release.name }}/g' ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}/.github/workflows/*.yaml

    - name: Push branch
      run: |
          cd ../${{ secrets.CHECKMARXDEV_KICS_RELEASER }}
          git add .
          git commit -m "AUTO: Add queries from release ${{ github.event.release.name }} to ${{ secrets.CHECKMARXDEV_KICS_RELEASER }}"
          git push origin ${{ github.event.release.name }}