name: release-kics-queries-repo-branch
on:
  release:
    types:
      - published
jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: "kics-queries-repo"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git credentials
      run: |
          git config --global user.name "KICSBot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://${{ secrets.CHECKMARXDEV_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Clone kics-queries-repo from CheckmarxDev
      run: |
          cd ..
          git clone https://github.com/CheckmarxDev/$REPO_NAME.git

    - name: Create new branch for release ${{ github.event.release.name }}
      run: |
          cd ../$REPO_NAME
          git checkout -b ${{ github.event.release.name }}

    - name: Copy queries to new branch
      run: |
          mkdir -p ../$REPO_NAME/kics-queries
          rsync -av --exclude='*/test/*' --exclude='common/*' ./assets/queries/ ../$REPO_NAME/kics-queries/

    - name: Modify circleci configuration
      run: |
          sed -i 's/branch_name_template_to_replace/${{ github.event.release.name }}/g' ../$REPO_NAME/.circleci/config.yml

    - name: Push branch
      run: |
          cd ../$REPO_NAME
          git add .
          git commit -m "Add queries from release ${{ github.event.release.name }} to $REPO_NAME"
          git push origin ${{ github.event.release.name }}
