name: release-kics-queries-repo-branch
on:
  release:
    types:
      - published
jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: "kics-queries-repo"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
          git config --global user.name "${{ github.actor }}"
          git config --global url."https://${{ secrets.CHECKMARXDEV_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Clone kics-queries-repo from CheckmarxDev
      run: |
          cd ..
          git clone https://github.com/CheckmarxDev/$REPO_NAME.git

    - name: Create new branch for release ${{ github.event.release.name }}
      run: |
          cd ../$REPO_NAME
          git checkout -b ${{ github.event.release.name }}

    - name: Copy queries to new branch
      run: |
          mkdir -p ../$REPO_NAME/kics-queries
          rsync -av --exclude='*/test/*' --exclude='common/*' ./assets/queries/ ../$REPO_NAME/kics-queries/

    - name: Copy circle ci configuration to new branch
      run: |
          mkdir -p ../$REPO_NAME/.circleci
          sed 's/branch_name_template_to_replace/${{ github.event.release.name }}/g' .github/scripts/kics-queries-repo-branch-creation/config-template/config.yml > .github/scripts/kics-queries-repo-branch-creation/config.yml
          cp .github/scripts/kics-queries-repo-branch-creation/config.yml ../$REPO_NAME/.circleci/

    - name: Push branch
      run: |
          cd ../$REPO_NAME
          git add .
          git commit -m "Add queries from release ${{ github.event.release.name }} to $REPO_NAME"
          git push origin ${{ github.event.release.name }}
