name: statistics

on:
  workflow_dispatch:
    
jobs:
  metrics:
    name: test-metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.4
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Run test metrics script
        id: testcoverage
        run: |
          make test-coverage-report | tee test-results
          TOTAL_TESTS=$(cat test-results | grep -v TestQueriesContent/ | grep -v TestQueriesMetadata/ | grep -v TestQueries/ | grep PASS | wc -l)
          echo "Total Tests :: ${TOTAL_TESTS}"
          echo "::set-output name=total_tests::${TOTAL_TESTS}"
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.x"
      - name: Run test statistics script
        id: metrics
        run: |
          python3 .github/scripts/statistics/get-statistics.py -c ${{steps.testcoverage.outputs.coverage}} -t ${{steps.testcoverage.outputs.total_tests}}
      
