name: update-docs-index

on:
  workflow_dispatch:
  release:
    type: [published]

jobs:
  update-index:
    name: Update index docs links
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Get current date
        id: cdate
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Get release version
        id: cversion
        run: |
          echo "::set-output name=version::$(git describe --tags --match='v*' --abbrev=0 | cut -c2-)"
      - name: Print variables
        run: |
          echo "Version :: ${{ steps.cversion.outputs.version }}"
          echo "Date :: ${{ steps.cdate.outputs.date }}"
      - name: Replace lines
        run: |
          sed -E -i "s/<h4>Version [0-9]+\.[0-9]+\.[0-9]+<\/h4>/<h4>Version ${{ steps.cversion.outputs.version }}<\/h4>/" docs/index.md
          sed -E -i "s/(<p.*>)[0-9]{4}\.[0-9]{2}\.[0-9]{2}<p>/\1${{ steps.cdate.outputs.date }}<p>/" docs/index.md
          sed -E -i "s/(<a.*href=\"https:\/\/github.com\/Checkmarx\/kics\/releases\/download\/).*(\/kics_).*(_[a-z]+_.*>)/\1v${{ steps.cversion.outputs.version }}\2${{ steps.cversion.outputs.version }}\3/g" docs/index.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.9.1
        with:
          title: "docs(index): updating links in index page - ${{ steps.cversion.outputs.version }}"
          token: ${{ secrets.KICS_BOT_PAT }}
          commit-message: "docs(index): updating links in index page"
          delete-branch: true
          branch: feature/kicsbot-update-docs-index
          base: master
          body: |
            **Automated Changes**
            Updating documentation index page.
            Triggered by SHA: _${{ github.sha }}_
          labels: documentation
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-bootswatch mike
      - name: Config KICSBot git user
        run: |
          git config --global user.name "KICSBot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy mike version
        run: |
          mike deploy ${{ steps.cversion.outputs.version }} latest -u
      - name: Fix version selector
        run: |
          git checkout gh-pages
          find . -type f -name "*.html" -exec sed -i -E '/<script src="(.)*js\/version-select.js" defer><\/script>/d' {} +
          find . -type f -name "*.html" -exec sed -i -E '/<link href="(.)*css\/version-select.css" rel="stylesheet"/d' {} +
          find . -type f -name "version-select.css" -exec rm -f {} +
          find . -type f -name "version-select.js" -exec rm -f {} +
          git commit -a --amend --no-edit
          git push origin gh-pages
