name: update-infra-version

on:
  workflow_dispatch:
  release:
    type: [published]

permissions:
  contents: read

jobs:
  update-infra-version:
    name: Updates infra with new release
    runs-on: cx-public-ubuntu-x64
    if: "!github.event.release.prerelease"
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Update Terraform Cloud Integration
        uses: step-security/repository-dispatch@1a81ac1c72a4ad222c516293b6adf56b34c4cffd # v4.0.2
        with:
          token: ${{ secrets.KICS_BOT_PAT }}
          repository: ${{ secrets.TFC_REPO_PATH }}
          event-type: new-release
      - name: Update Infra
        uses: step-security/repository-dispatch@1a81ac1c72a4ad222c516293b6adf56b34c4cffd # v4.0.2
        with:
          token: ${{ secrets.KICS_BOT_PAT }}
          repository: ${{ secrets.INFRA_REPO }}
          event-type: new-release
