name: update-docs-index

on:
  workflow_dispatch:
  release:
    type: [published]

jobs:
  update-index:
    name: Update index docs links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Get release version
        id: current-version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0 | cut -c2-)"
      - name: Replace lines
        run: |
          sed -E -i "s/<h4>Version [0-9]+\.[0-9]+\.[0-9]+<\/h4>/<h4>Version ${{ steps.current-version.version }}<\/h4>/" docs/index.md
          sed -E -i "s/(<p.*>)[0-9]{4}\.[0-9]{2}\.[0-9]{2}<p>/\1${{ steps.current-date.date }}<p>/" docs/index.md
          sed -E -i "s/(<a.*href=\"https:\/\/github.com\/Checkmarx\/kics\/releases\/download\/).*(\/kics_).*(_[a-z]+_.*>)/\1${{ steps.current-version.version }}\2${{ steps.current-version.version }}\3/g" docs/index.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update documentation index page - ${{ steps.current-version.version }}
          env:
            GITHUB_TOKEN: ${{ secrets.KICS_BOT_PAT }}
          body: |
            **Automated changes**
            Updating documentation index page.
            Triggered by SHA: _${{ github.sha }}_
          labels: documentation
