name: validate-rego

on:
  pull_request:
    paths:
      - "assets/**/*.rego"

jobs:
  lint-rego:
    name: Run Regal Linter on Rego Files
    runs-on: ubuntu-latest
    env:
      REGO_FILES_PATH: assets
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Regal
        uses: StyraInc/setup-regal@v1.0.0
        with:
          version: v0.11.0
      - name: Run Regal Linter
        run: regal lint --config kics/assets/.regal/rego_config.yaml --format=github ${{ env.REGO_FILES_PATH }}
