name: validate-ansible-azure-samples

on:
  pull_request:
    paths:
    - "assets/queries/ansible/azure/**/test/*.yaml"

jobs:
  validate-azr-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: assets/queries/ansible/azure
          config_file: .github/yamllint.yml
