name: validate-ansible-samples

on:
  pull_request:
    paths:
    - "assets/queries/ansible/aws/**/test/*.yaml"
    - "assets/queries/ansible/azure/**/test/*.yaml"
    - "assets/queries/ansible/gcp/**/test/*.yaml"

permissions:
  contents: read

jobs:
  lint-samples:
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: yaml-lint
        uses: step-security/action-yamllint@f6001007aa934824354a24f099a6f97cf6472e15 # v3.1.1
        with:
          file_or_dir: assets/queries/ansible/
          config_file: .github/scripts/samples-linters/yamllint_ansible.yml
          strict: true
