name: validate-rego

on:
  pull_request:
    paths:
      - "assets/**/*.rego"

jobs:
  lint-rego:
    name: Run Regal Linter on Rego Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup Regal
        uses: StyraInc/setup-regal@33a142b1189004e0f14bf42b15972c67eecce776 # v1.0.0
        with:
          version: v0.31.1

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run Regal Linter
        run: regal lint --format=github assets --config-file=assets/.regal/config.yml

      - name: Format .rego Files
        run: |
          opa fmt -w assets/**/*.rego
          git diff --exit-code
